name: "Translations"

on:
  pull_request:
  push:
    branches:
      - master
      - 2.*

permissions:
  contents: read

jobs:
  translations:
    name: "Translations"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: pecl, composer:2.2
          extensions: pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, curl, imagick, pgsql, gd, tidy
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--optimize-autoloader --prefer-dist"

      - name: "Validate Core translations"
        run: "php bin/console lint:yaml src/Wallabag/CoreBundle/Resources/translations -v"

      - name: "Validate CraueConfig translations"
        run: "php bin/console lint:yaml app/Resources/CraueConfigBundle/translations -v"

      - name: "Validate User translations"
        run: "php bin/console lint:yaml src/Wallabag/UserBundle/Resources/translations -v"
